title: MABUHAY
author: Cess R.
email: rcessrdrgz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am 22 year-old fresh graduate of Electronics and Communications Engineering. Born and raised from the land of hospitable people, the Philippines, and now achieving her goals in Virginia, USA. 
  I also have a passion in singing. If you wanna hear me sing, visit my Youtube channel. I can speak Tagalog, English and a little bit of Korean.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
